name: WuhuApp

options:
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 97W7A3Y9GD

packages:
  Wuhu:
    path: ..
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.23.1
  SwiftCollections:
    url: https://github.com/apple/swift-collections
    from: 1.3.0
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: 1.7.2
  IdentifiedCollections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: 1.1.1
  Clocks:
    url: https://github.com/pointfreeco/swift-clocks
    from: 1.0.6
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 1.11.0
  ConcurrencyExtras:
    url: https://github.com/pointfreeco/swift-concurrency-extras
    from: 1.3.2
  CustomDump:
    url: https://github.com/pointfreeco/swift-custom-dump
    from: 1.4.1
  CombineSchedulers:
    url: https://github.com/pointfreeco/combine-schedulers
    from: 1.1.0
  Sharing:
    url: https://github.com/pointfreeco/swift-sharing
    from: 2.7.4
  SwiftNavigation:
    url: https://github.com/pointfreeco/swift-navigation
    from: 2.6.0
  XCTestDynamicOverlay:
    url: https://github.com/pointfreeco/xctest-dynamic-overlay
    from: 1.8.1

targets:
  WuhuApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - Info-macOS.plist
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Wuhu
        CFBundleIconName: AppIcon
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ms.liu.wuhu.ios
        IPHONEOS_DEPLOYMENT_TARGET: "26.0"
    dependencies:
      - package: Wuhu
        product: WuhuClient
      - package: Wuhu
        product: WuhuAPI
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SwiftCollections
        product: OrderedCollections
      - package: CasePaths
        product: CasePaths
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Clocks
        product: Clocks
      - package: Dependencies
        product: Dependencies
      - package: ConcurrencyExtras
        product: ConcurrencyExtras
      - package: CustomDump
        product: CustomDump
      - package: CombineSchedulers
        product: CombineSchedulers
      - package: Sharing
        product: Sharing
      - package: SwiftNavigation
        product: SwiftUINavigation
      - package: SwiftNavigation
        product: UIKitNavigation
      - package: XCTestDynamicOverlay
        product: IssueReporting
      - package: XCTestDynamicOverlay
        product: XCTestDynamicOverlay

  WuhuAppMac:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
    info:
      path: Sources/Info-macOS.plist
      properties:
        CFBundleDisplayName: Wuhu
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ms.liu.wuhu.macos
        MACOSX_DEPLOYMENT_TARGET: "26.0"
    dependencies:
      - package: Wuhu
        product: WuhuClient
      - package: Wuhu
        product: WuhuAPI
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SwiftCollections
        product: OrderedCollections
      - package: CasePaths
        product: CasePaths
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Clocks
        product: Clocks
      - package: Dependencies
        product: Dependencies
      - package: ConcurrencyExtras
        product: ConcurrencyExtras
      - package: CustomDump
        product: CustomDump
      - package: CombineSchedulers
        product: CombineSchedulers
      - package: Sharing
        product: Sharing
      - package: SwiftNavigation
        product: SwiftUINavigation
      - package: XCTestDynamicOverlay
        product: IssueReporting
      - package: XCTestDynamicOverlay
        product: XCTestDynamicOverlay

  WuhuAppTests:
    type: bundle.unit-test
    platform: iOS
    sources:
      - path: Tests
    settings:
      base:
        GENERATE_INFOPLIST_FILE: YES
    dependencies:
      - target: WuhuApp
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: SwiftCollections
        product: OrderedCollections
      - package: CasePaths
        product: CasePaths
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Clocks
        product: Clocks
      - package: Dependencies
        product: Dependencies
      - package: ConcurrencyExtras
        product: ConcurrencyExtras
      - package: CustomDump
        product: CustomDump
      - package: CombineSchedulers
        product: CombineSchedulers
      - package: Sharing
        product: Sharing
      - package: SwiftNavigation
        product: SwiftUINavigation
      - package: SwiftNavigation
        product: UIKitNavigation
      - package: XCTestDynamicOverlay
        product: IssueReporting
      - package: XCTestDynamicOverlay
        product: XCTestDynamicOverlay
