name: WuhuApp

options:
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 97W7A3Y9GD

packages:
  Wuhu:
    path: ..
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.23.1
  IdentifiedCollections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: 1.1.1
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 1.11.0
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: 1.7.2
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.0

targets:
  WuhuApp:
    type: application
    platform: iOS
    sources:
      - path: Sources
        excludes:
          - Info-macOS.plist
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Wuhu
        CFBundleIconName: AppIcon
        UILaunchScreen: {}
        ITSAppUsesNonExemptEncryption: false
        UISupportedInterfaceOrientations:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
        UISupportedInterfaceOrientations~ipad:
          - UIInterfaceOrientationPortrait
          - UIInterfaceOrientationPortraitUpsideDown
          - UIInterfaceOrientationLandscapeLeft
          - UIInterfaceOrientationLandscapeRight
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ms.liu.wuhu.ios
        IPHONEOS_DEPLOYMENT_TARGET: "18.0"
        SWIFT_VERSION: "6.0"
        DISABLE_DIAMOND_PROBLEM_DIAGNOSTIC: YES
    dependencies:
      - package: Wuhu
        product: WuhuAPI
      - package: Wuhu
        product: WuhuClient
      - package: Wuhu
        product: WuhuCoreClient
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: MarkdownUI
        product: MarkdownUI

  WuhuAppMac:
    type: application
    platform: macOS
    sources:
      - path: Sources
        excludes:
          - Info.plist
    info:
      path: Sources/Info-macOS.plist
      properties:
        CFBundleDisplayName: Wuhu
        CFBundleIconName: AppIcon
        ITSAppUsesNonExemptEncryption: false
        NSMainStoryboardFile: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ms.liu.wuhu.macos
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "6.0"
    dependencies:
      - package: Wuhu
        product: WuhuAPI
      - package: Wuhu
        product: WuhuClient
      - package: Wuhu
        product: WuhuCoreClient
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: MarkdownUI
        product: MarkdownUI
