name: WuhuMVPApp

options:
  createIntermediateGroups: true
  generateEmptyDirectories: true

settings:
  base:
    CODE_SIGN_STYLE: Automatic
    DEVELOPMENT_TEAM: 97W7A3Y9GD

packages:
  Wuhu:
    path: ..
  ComposableArchitecture:
    url: https://github.com/pointfreeco/swift-composable-architecture
    from: 1.23.1
  IdentifiedCollections:
    url: https://github.com/pointfreeco/swift-identified-collections
    from: 1.1.1
  Dependencies:
    url: https://github.com/pointfreeco/swift-dependencies
    from: 1.11.0
  CasePaths:
    url: https://github.com/pointfreeco/swift-case-paths
    from: 1.7.2
  MarkdownUI:
    url: https://github.com/gonzalezreal/swift-markdown-ui
    from: 2.4.0

targets:
  WuhuMVPApp:
    type: application
    platform: macOS
    sources:
      - path: Sources
    info:
      path: Sources/Info.plist
      properties:
        CFBundleDisplayName: Wuhu
        CFBundleIconName: AppIcon
        NSMainStoryboardFile: ""
    settings:
      base:
        PRODUCT_BUNDLE_IDENTIFIER: ms.liu.wuhu.mvp
        MACOSX_DEPLOYMENT_TARGET: "15.0"
        SWIFT_VERSION: "6.0"
    dependencies:
      - package: Wuhu
        product: WuhuAPI
      - package: Wuhu
        product: WuhuClient
      - package: ComposableArchitecture
        product: ComposableArchitecture
      - package: IdentifiedCollections
        product: IdentifiedCollections
      - package: Dependencies
        product: Dependencies
      - package: CasePaths
        product: CasePaths
      - package: MarkdownUI
        product: MarkdownUI
