// Adapted from pointfreeco/sqlite-data (MIT License). See SQLiteQueryDecoder.swift.
import Foundation
import GRDB
import GRDBSQLite
import StructuredQueriesCore

class QueryCursor<Element>: DatabaseCursor {
  var _isDone: Bool = false
  let _statement: GRDB.Statement
  var decoder: SQLiteQueryDecoder

  init(db: Database, query: QueryFragment) throws {
    (_statement, decoder) = try db.prepare(query: query)
  }

  deinit {
    sqlite3_reset(_statement.sqliteStatement)
  }

  func _element(sqliteStatement _: SQLiteStatement) throws -> Element {
    fatalError("Abstract method should be overridden in subclass")
  }

  struct DecodingError: Error, CustomStringConvertible {
    let columnIndex: Int
    let columnName: String
    let sql: String

    var description: String {
      """
      Expected column \(columnIndex) (\(columnName.debugDescription)) to not be NULL: …

      \(sql)
      """
    }
  }
}

final class QueryValueCursor<QueryValue: QueryRepresentable>: QueryCursor<QueryValue.QueryOutput> {
  typealias Element = QueryValue.QueryOutput

  override func _element(sqliteStatement _: SQLiteStatement) throws -> Element {
    do {
      let element = try QueryValue(decoder: &decoder).queryOutput
      decoder.next()
      return element
    } catch QueryDecodingError.missingRequiredColumn {
      let columnIndex = Int(decoder.currentIndex) - 1
      throw DecodingError(
        columnIndex: columnIndex,
        columnName: _statement.columnNames[columnIndex],
        sql: _statement.sql,
      )
    }
  }
}

final class QueryVoidCursor: QueryCursor<Void> {
  typealias Element = ()

  override func _element(sqliteStatement _: SQLiteStatement) throws {
    try decoder.decodeColumns(Void.self)
    decoder.next()
  }
}

extension Database {
  func prepare(query: QueryFragment) throws -> (GRDB.Statement, SQLiteQueryDecoder) {
    var (sql, bindings) = query.prepare { _ in "?" }
    if sql.isEmpty {
      sql = "SELECT 1 WHERE 0 -- Empty query generated by StructuredQueries"
    }
    let statement = try makeStatement(sql: sql)
    statement.arguments = try StatementArguments(bindings.map { try $0.databaseValue })
    return (
      statement,
      SQLiteQueryDecoder(statement: statement.sqliteStatement),
    )
  }
}

extension QueryBinding {
  var databaseValue: DatabaseValue {
    get throws {
      switch self {
      case .blob(let blob):
        return Data(blob).databaseValue
      case .bool(let bool):
        return (bool ? 1 : 0).databaseValue
      case .date(let date):
        return SQLiteDateFormat.string(from: date).databaseValue
      case .double(let double):
        return double.databaseValue
      case .int(let int):
        return int.databaseValue
      case .null:
        return .null
      case .text(let text):
        return text.databaseValue
      case .uint(let uint) where uint <= UInt64(Int64.max):
        return uint.databaseValue
      case .uint(let uint):
        throw Int64OverflowError(unsignedInteger: uint)
      case .uuid(let uuid):
        return uuid.uuidString.lowercased().databaseValue
      case .invalid(let error):
        throw error
      }
    }
  }
}

struct Int64OverflowError: Error {
  let unsignedInteger: UInt64
}
