import { basename, join } from '@std/path'

// A package's own module-level declarations (pinned http_archives it alone
// uses) live beside its package.yml, so the root template stays free of any one
// product and a subset of packages carries only its own.
export const packageModuleFragment = 'MODULE.fragment.bazel'

// One `swift_deps.configure_package` per file, named after the rspm repo it
// configures. A block is emitted only when the umbrella lockfile pins that
// repo, so a graph without the package carries no configuration for it.
export const configureFragmentDir = 'bazel/umbrella/configure'

// The external repositories a MODULE.fragment.bazel declares: the `name` of
// each top-level call. A build_file_content string holds its own targets'
// names, so string literals are dropped first.
export function moduleFragmentRepos(text: string): string[] {
  const code = text.replace(/"""[\s\S]*?"""/g, '""')
  return [...code.matchAll(/^\s+name = "([^"]+)",$/gm)].map((match) => match[1])
}

export interface ModuleFragment {
  source: string
  text: string
}

// rspm names each pinned SwiftPM package `swiftpkg_` + identity with `-` -> `_`.
export function pinnedRepos(lockfileJson: string): Set<string> {
  const lockfile = JSON.parse(lockfileJson) as {
    pins?: { identity?: string }[]
  }
  return new Set(
    (lockfile.pins ?? []).flatMap((pin) =>
      pin.identity ? [`swiftpkg_${pin.identity.replace(/-/g, '_')}`] : []
    ),
  )
}

export function configureFragmentRepo(fragment: ModuleFragment): string {
  const repo = basename(fragment.source).replace(/\.bazel$/, '')
  const names = [...fragment.text.matchAll(/^\s+name = "([^"]+)",$/gm)]
    .map((match) => match[1])
  if (names.length !== 1 || names[0] !== repo) {
    throw new Error(
      `${fragment.source} must hold exactly one configure_package for ${repo}, found ${
        JSON.stringify(names)
      }.`,
    )
  }
  return repo
}

// `strict` is the whole-repo run: a block for a repo nothing pins is stale and
// fails. A subset run drops it, since that is exactly what the subset is for.
export function renderModuleBazel(options: {
  template: string
  swiftDepsRepos: readonly string[]
  packageModules: readonly ModuleFragment[]
  configure: readonly ModuleFragment[]
  pinned: ReadonlySet<string>
  strict: boolean
}): string {
  const configure: string[] = []
  for (const fragment of options.configure) {
    const repo = configureFragmentRepo(fragment)
    if (options.pinned.has(repo)) {
      configure.push(fragment.text.trimEnd())
    } else if (options.strict) {
      throw new Error(
        `${fragment.source} configures ${repo}, which bazel/umbrella/Package.resolved does not pin; delete it or re-resolve.`,
      )
    }
  }
  const replacements: Record<string, string> = {
    '{{swift_deps_repos}}': options.swiftDepsRepos.map((repo) =>
      `    "${repo}",`
    ).join('\n'),
    '{{package_modules}}': options.packageModules.map((fragment) =>
      `# From ${fragment.source}.\n${fragment.text.trimEnd()}`
    ).join('\n\n'),
    '{{swift_deps_configure}}': configure.join('\n'),
  }
  let rendered = options.template
  for (const [placeholder, value] of Object.entries(replacements)) {
    if (rendered.split(placeholder).length !== 2) {
      throw new Error(
        `MODULE.bazel.template must contain ${placeholder} exactly once.`,
      )
    }
    rendered = rendered.replace(placeholder, () => value)
  }
  // An empty fragment list leaves its placeholder line blank; keep the
  // generated file free of runs of blank lines.
  return `# Generated by deno task generate-manifests from MODULE.bazel.template. Do not edit.\n\n${
    rendered.replace(/\n{3,}/g, '\n\n')
  }`
}

async function readIfPresent(path: string): Promise<string | undefined> {
  try {
    return await Deno.readTextFile(path)
  } catch (error) {
    if (error instanceof Deno.errors.NotFound) return undefined
    throw error
  }
}

export async function readPackageModules(
  packageDirs: readonly string[],
): Promise<ModuleFragment[]> {
  const fragments: ModuleFragment[] = []
  for (const dir of [...packageDirs].sort()) {
    const source = join(dir, packageModuleFragment)
    const text = await readIfPresent(source)
    if (text !== undefined) fragments.push({ source, text })
  }
  return fragments
}

export async function readConfigureFragments(): Promise<ModuleFragment[]> {
  const fragments: ModuleFragment[] = []
  try {
    for await (const entry of Deno.readDir(configureFragmentDir)) {
      if (!entry.isFile || !entry.name.endsWith('.bazel')) continue
      const source = join(configureFragmentDir, entry.name)
      fragments.push({ source, text: await Deno.readTextFile(source) })
    }
  } catch (error) {
    if (!(error instanceof Deno.errors.NotFound)) throw error
  }
  return fragments.sort((lhs, rhs) => lhs.source.localeCompare(rhs.source))
}
