import type {
  AppBundleManifest,
  AppLibraryManifest,
  AppManifest,
  PlistValue,
} from './generate.ts'
import { appProfileName, entitlementPath, variantBundle } from './generate.ts'

export interface LocalPackageRef {
  // The SwiftPM package name, which is also the xcodegen `packages:` key.
  name: string
  products: string[]
  // Path to the package directory, relative to the app-shell directory.
  path: string
}

export interface XcodeProjectSpec {
  spec: Record<string, unknown>
  unresolved: string[]
}

const bundleSourceExtensions = ['.xcassets', '.icon']

export interface AppIconSource {
  path: string
  name: string
}

// `appIcons` are Bazel globs into an asset catalog or an Icon Composer bundle;
// Xcode wants the enclosing bundle as a source and the icon set's base name as
// ASSETCATALOG_COMPILER_APPICON_NAME.
export function appIconSource(pattern: string): AppIconSource | undefined {
  const components = pattern.split('/')
  const index = components.findIndex((component) =>
    bundleSourceExtensions.some((extension) => component.endsWith(extension))
  )
  if (index < 0) return undefined
  const bundle = components[index]
  const path = components.slice(0, index + 1).join('/')
  if (bundle.endsWith('.icon')) {
    return { path, name: stripExtension(bundle) }
  }
  const iconSet = components[index + 1]
  if (!iconSet || iconSet === '**') return undefined
  return { path, name: stripExtension(iconSet) }
}

function stripExtension(name: string): string {
  const dot = name.lastIndexOf('.')
  return dot <= 0 ? name : name.slice(0, dot)
}

// Bazel accepts a resource path inside a bundle source (an imageset in a
// catalog); Xcode only takes the enclosing bundle.
export function resourceSourcePath(path: string): string {
  const components = path.split('/')
  const index = components.findIndex((component) =>
    bundleSourceExtensions.some((extension) => component.endsWith(extension))
  )
  return index < 0 ? path : components.slice(0, index + 1).join('/')
}

// Xcode with GENERATE_INFOPLIST_FILE=NO does not add CFBundleExecutable, and
// installd rejects a bundle without it. The workspace plist therefore adds the
// one Xcode-specific value after the common app-manifest defaults are resolved.
export function xcodeInfoPlist(
  info: { [key: string]: PlistValue },
): { [key: string]: PlistValue } {
  return { CFBundleExecutable: '$(EXECUTABLE_NAME)', ...info }
}

export function xcodeInfoPlistPath(target: AppBundleManifest): string {
  return `.xcodegen/${target.name}-Info.plist`
}

// Xcode links an app target's debug dylib and __preview.dylib with
// -no_adhoc_codesign and signs them in follow-up tasks — but it only emits
// those tasks for a target that compiles sources of its own. A shell whose
// whole binary arrives through package products therefore ships an unsigned
// Contents/MacOS/<App>.debug.dylib, and the bundle's own CodeSign dies with
// "code object is not signed at all". One compiled source is the entire fix.
export function xcodeShellSourcePath(target: AppBundleManifest): string {
  return `.xcodegen/${target.name}-XcodeShell.swift`
}

export function xcodeShellSource(target: AppBundleManifest): string {
  const name = target.name.replace(/[^A-Za-z0-9_]/g, '')
  return [
    '// Generated by tools/manifest-gen — do not edit.',
    '//',
    '// The app shell compiles nothing of its own, and an Xcode target with no',
    '// compiled sources never gets the CodeSign tasks for its debug dylib and',
    '// __preview.dylib, which makes the bundle signature fail. This empty',
    '// declaration is here so the target has something to compile.',
    `enum ${name}XcodeShell {}`,
    '',
  ].join('\n')
}

const deviceFamilies: Record<string, string> = {
  iphone: '1',
  ipad: '2',
  tv: '3',
  watch: '4',
  vision: '7',
}

export function targetedDeviceFamily(families: string[]): string | undefined {
  const identifiers = families
    .map((family) => deviceFamilies[family])
    .filter((identifier): identifier is string => identifier !== undefined)
  return identifiers.length ? identifiers.join(',') : undefined
}

interface ResolvedDependencies {
  sources: string[]
  packageProducts: { package: string; product: string }[]
  unresolved: string[]
}

function resolveDependencies(
  target: AppBundleManifest,
  libraries: Map<string, AppLibraryManifest>,
  packages: Record<string, LocalPackageRef>,
): ResolvedDependencies {
  const sources: string[] = []
  const packageProducts: { package: string; product: string }[] = []
  const unresolved: string[] = []
  const seen = new Set<string>()
  const queue = [...target.dependencies]

  while (queue.length) {
    const dependency = queue.shift()!
    if (seen.has(dependency)) continue
    seen.add(dependency)

    if (dependency.startsWith(':')) {
      const library = libraries.get(dependency.slice(1))
      if (!library) {
        throw new Error(
          `${target.name} depends on ${dependency}, which no library declares`,
        )
      }
      const librarySources = typeof library.sources === 'string'
        ? [library.sources]
        : library.sources
      sources.push(...librarySources)
      queue.push(...(library.dependencies ?? []))
      continue
    }

    const match = /^\/\/(.+):(.+)$/.exec(dependency)
    const local = match ? packages[match[1]] : undefined
    if (!match || !local || !local.products.includes(match[2])) {
      unresolved.push(dependency)
      continue
    }
    packageProducts.push({ package: local.name, product: match[2] })
  }

  return {
    sources: [...new Set(sources)],
    packageProducts,
    unresolved,
  }
}

function targetSpec(
  app: AppManifest,
  declared: AppBundleManifest,
  resolved: ResolvedDependencies,
  teamID: string | undefined,
  launchArguments: string[],
  type: 'application' | 'app-extension',
  embeddedExtensions: string[] = [],
): Record<string, unknown> {
  const target = variantBundle(declared, 'dev')
  const icons = target.appIcons
    .map(appIconSource)
    .filter((icon): icon is AppIconSource => icon !== undefined)
  const resourcePaths = new Set([
    ...icons.map((icon) => icon.path),
    ...(target.resources ?? []).map(resourceSourcePath),
  ])
  const sources = [
    // The Bazel plist generator writes into the shell's source directory, so a
    // library rooted there would otherwise copy it into the bundle twice.
    ...resolved.sources.map((path) => ({
      path,
      excludes: ['**/BazelInfo*.plist'],
    })),
    ...[...resourcePaths].map((path) => ({ path })),
    { path: xcodeShellSourcePath(target) },
  ]

  const settings: Record<string, string> = {
    PRODUCT_BUNDLE_IDENTIFIER: target.bundleID,
    PRODUCT_NAME: target.bundleName,
    INFOPLIST_FILE: xcodeInfoPlistPath(target),
    GENERATE_INFOPLIST_FILE: 'NO',
    CODE_SIGN_ENTITLEMENTS: entitlementPath(
      declared,
      declared.distribution === 'direct' ? 'store' : 'dev',
    ),
    CODE_SIGN_STYLE: 'Manual',
    SWIFT_VERSION: '6.0',
  }
  if (teamID) settings.DEVELOPMENT_TEAM = teamID
  const profile = appProfileName(app, declared, 'dev')
  if (profile) settings.PROVISIONING_PROFILE_SPECIFIER = profile
  // app.yml `linkopts:` are linker arguments (the ffmpeg frameworks' flat
  // `@rpath/<name>` install names need one -rpath per framework directory, for
  // one). Bazel hands them to the linker; Xcode gets the same list through
  // OTHER_LDFLAGS, so a workspace build loads what a Bazel build loads.
  if (target.linkopts?.length) {
    settings.OTHER_LDFLAGS = [
      '$(inherited)',
      ...target.linkopts.map((option) => `-Wl,${option}`),
    ].join(' ')
  }
  const family = targetedDeviceFamily(target.families)
  if (family) settings.TARGETED_DEVICE_FAMILY = family
  if (icons.length) settings.ASSETCATALOG_COMPILER_APPICON_NAME = icons[0].name

  return {
    type,
    platform: target.platform,
    deploymentTarget: target.minimumOSVersion,
    sources,
    dependencies: [
      ...resolved.packageProducts.map((entry) => ({
        package: entry.package,
        product: entry.product,
      })),
      ...embeddedExtensions.map((target) => ({ target })),
    ],
    settings: { base: settings },
    scheme: {
      testTargets: [],
      ...(launchArguments.length
        ? {
          commandLineArguments: Object.fromEntries(
            launchArguments.map((argument) => [argument, true]),
          ),
        }
        : {}),
    },
  }
}

// Per-machine scheme knobs, read from the untracked
// `Apps/<shell>/.xcodegen-local.yml` (e.g. a -seedLibrary pointing at this
// machine's mount) — scheme edits made in Xcode die on every regeneration,
// so anything worth keeping belongs there.
export interface WorkspaceLocalConfig {
  launchArguments?: string[]
}

export function xcodeProjectSpec(
  app: AppManifest,
  packages: Record<string, LocalPackageRef>,
  local: WorkspaceLocalConfig = {},
): XcodeProjectSpec {
  const libraries = new Map(
    (app.libraries ?? []).map((library) => [library.name, library]),
  )
  const teamID = app.signingTeamID
  const targets: Record<string, unknown> = {}
  const unresolved: string[] = []
  const usedPackages = new Set<string>()

  for (const extension of app.extensions ?? []) {
    const resolved = resolveDependencies(extension, libraries, packages)
    for (const entry of resolved.packageProducts) {
      usedPackages.add(entry.package)
    }
    unresolved.push(
      ...resolved.unresolved.map((name) => `${extension.name}: ${name}`),
    )
    targets[extension.name] = targetSpec(
      app,
      extension,
      resolved,
      teamID,
      local.launchArguments ?? [],
      'app-extension',
    )
  }

  for (const watch of app.watchApplications ?? []) {
    const resolved = resolveDependencies(watch, libraries, packages)
    for (const entry of resolved.packageProducts) {
      usedPackages.add(entry.package)
    }
    unresolved.push(
      ...resolved.unresolved.map((name) => `${watch.name}: ${name}`),
    )
    targets[watch.name] = targetSpec(
      app,
      watch,
      resolved,
      teamID,
      local.launchArguments ?? [],
      'application',
    )
  }

  for (const target of app.targets) {
    const resolved = resolveDependencies(target, libraries, packages)
    for (const entry of resolved.packageProducts) {
      usedPackages.add(entry.package)
    }
    unresolved.push(
      ...resolved.unresolved.map((name) => `${target.name}: ${name}`),
    )
    targets[target.name] = targetSpec(
      app,
      target,
      resolved,
      teamID,
      local.launchArguments ?? [],
      'application',
      [
        ...(target.extensions ?? []),
        ...(target.watchApplication === undefined
          ? []
          : [target.watchApplication]),
      ],
    )
  }

  const specPackages: Record<string, unknown> = {}
  for (const local of Object.values(packages)) {
    if (usedPackages.has(local.name)) {
      specPackages[local.name] = {
        path: local.path,
      }
    }
  }

  return {
    spec: {
      name: app.name,
      options: {
        createIntermediateGroups: true,
        // The .xcodeproj is derived and untracked; there is no second machine
        // to keep its file ordering stable for.
        generateEmptyDirectories: false,
      },
      packages: specPackages,
      targets,
    },
    unresolved,
  }
}

export function workspaceContents(
  packagePath: string,
  projectPaths: string[],
): string {
  const refs = [packagePath, ...projectPaths]
    .map((path) =>
      `   <FileRef
      location = "group:${path}">
   </FileRef>`
    )
    .join('\n')
  return `<?xml version="1.0" encoding="UTF-8"?>
<Workspace
   version = "1.0">
${refs}
</Workspace>
`
}
