export interface Schema {
  title?: string
  type?: string | string[]
  enum?: unknown[]
  const?: unknown
  oneOf?: Schema[]
  anyOf?: Schema[]
  properties?: Record<string, Schema>
  required?: string[]
  items?: Schema
}

const HEADER =
  '// @generated by tools/contract-ts/emit.ts from the contract JSON Schema fixtures. Do not edit.\n'

class UnsupportedSchema extends Error {
  constructor(context: string, schema: Schema) {
    super(
      `contract-ts: unsupported schema construct at ${context}: ${
        JSON.stringify(schema)
      }`,
    )
    this.name = 'UnsupportedSchema'
  }
}

function literal(value: unknown): string {
  if (
    typeof value !== 'string' && typeof value !== 'number' &&
    typeof value !== 'boolean'
  ) {
    throw new Error(
      `contract-ts: unsupported literal ${JSON.stringify(value)}`,
    )
  }
  return JSON.stringify(value)
}

function isEmpty(schema: Schema): boolean {
  return schema.type === undefined && schema.enum === undefined &&
    schema.const === undefined && schema.oneOf === undefined &&
    schema.anyOf === undefined &&
    schema.properties === undefined && schema.items === undefined
}

function isUnion(schema: Schema): boolean {
  return schema.oneOf !== undefined || schema.anyOf !== undefined ||
    schema.enum !== undefined || Array.isArray(schema.type)
}

function propertyKey(name: string): string {
  return /^[A-Za-z_$][A-Za-z0-9_$]*$/.test(name) ? name : JSON.stringify(name)
}

function renderScalar(
  type: string,
  schema: Schema,
  context: string,
  indent: string,
): string {
  switch (type) {
    case 'null':
      return 'null'
    case 'string':
      return 'string'
    case 'integer':
    case 'number':
      return 'number'
    case 'boolean':
      return 'boolean'
    case 'object':
      return renderObject(schema, context, indent)
    case 'array': {
      const items = schema.items
      if (items === undefined) throw new UnsupportedSchema(context, schema)
      const inner = renderType(items, `${context}[]`, indent)
      return isUnion(items) ? `(${inner})[]` : `${inner}[]`
    }
    default:
      throw new UnsupportedSchema(context, schema)
  }
}

function renderObject(schema: Schema, context: string, indent: string): string {
  if (schema.properties === undefined) {
    throw new UnsupportedSchema(context, schema)
  }
  const required = new Set(schema.required ?? [])
  const inner = `${indent}  `
  const lines = Object.entries(schema.properties).map(([name, property]) => {
    const optional = required.has(name) ? '' : '?'
    const value = renderType(property, `${context}.${name}`, inner)
    return `${inner}${propertyKey(name)}${optional}: ${value};`
  })
  return `{\n${lines.join('\n')}\n${indent}}`
}

export function renderType(
  schema: Schema,
  context: string,
  indent: string,
): string {
  if (isEmpty(schema)) return 'unknown'
  if (schema.const !== undefined) return literal(schema.const)
  if (schema.enum !== undefined) {
    if (schema.type !== 'string') throw new UnsupportedSchema(context, schema)
    return schema.enum.map(literal).join(' | ')
  }
  const union = schema.oneOf ?? schema.anyOf
  if (union !== undefined) {
    return union
      .map((branch, index) => renderType(branch, `${context}|${index}`, indent))
      .join(' | ')
  }
  const type = schema.type
  if (type === undefined) throw new UnsupportedSchema(context, schema)
  if (Array.isArray(type)) {
    return type.map((one) => renderScalar(one, schema, context, indent)).join(
      ' | ',
    )
  }
  return renderScalar(type, schema, context, indent)
}

function renderDeclaration(schema: Schema): string {
  const title = schema.title
  if (title === undefined) {
    throw new Error(
      `contract-ts: schema is missing a title: ${JSON.stringify(schema)}`,
    )
  }
  if (schema.type === 'object' && schema.properties !== undefined) {
    return `export interface ${title} ${renderObject(schema, title, '')}`
  }
  return `export type ${title} = ${renderType(schema, title, '')};`
}

export function emitContract(schemas: Schema[]): string {
  const sorted = [...schemas].sort((lhs, rhs) => {
    const left = lhs.title ?? ''
    const right = rhs.title ?? ''
    return left < right ? -1 : left > right ? 1 : 0
  })
  const declarations = sorted.map(renderDeclaration).join('\n\n')
  return `${HEADER}\n${declarations}\n`
}

async function readFixtures(dir: string): Promise<Schema[]> {
  const files: string[] = []
  for await (const entry of Deno.readDir(dir)) {
    if (!entry.isDirectory && entry.name.endsWith('.schema.json')) {
      files.push(entry.name)
    }
  }
  files.sort()
  const schemas: Schema[] = []
  for (const name of files) {
    const text = await Deno.readTextFile(`${dir}/${name}`)
    schemas.push(JSON.parse(text) as Schema)
  }
  return schemas
}

function parseArgs(args: string[]): { dir: string; out: string | undefined } {
  let out: string | undefined
  const positional: string[] = []
  for (let index = 0; index < args.length; index++) {
    const arg = args[index]
    if (arg === '--out') {
      out = args[++index]
    } else if (arg.startsWith('--out=')) {
      out = arg.slice('--out='.length)
    } else {
      positional.push(arg)
    }
  }
  if (positional.length !== 1) {
    throw new Error('usage: emit.ts <fixtures-dir> [--out <file>]')
  }
  return { dir: positional[0], out }
}

if (import.meta.main) {
  const { dir, out } = parseArgs(Deno.args)
  const schemas = await readFixtures(dir)
  const output = emitContract(schemas)
  if (out === undefined) {
    await Deno.stdout.write(new TextEncoder().encode(output))
  } else {
    await Deno.writeTextFile(out, output)
  }
}
