import JSONValue
import QuickJSKit
import SessionDomain
import SpaceTools

let scriptImageConcurrency = 4

// wuhu:ai: model calls a script can make. Generated bytes go straight to their
// destination; the script gets only the metadata.
struct ScriptAI {
  let session: SessionID
  let tools: ToolExecutor

  func install(in engine: JSEngine) throws {
    let claims = MachineWriteClaims()
    engine.define("__wuhu_generate_image", promising: { [session, tools] arguments in
      guard case let .string(prompt)? = arguments.first, case let .string(destination)? = arguments.last else {
        throw ScriptError("malformed generateImage call")
      }
      let image: GeneratedImage
      do {
        image = try await tools.generateImage(session, prompt: prompt, destination: destination, claims: claims)
      } catch let problem as ToolProblem {
        throw ScriptError(problem.message)
      } catch is CancellationError {
        throw CancellationError()
      } catch {
        throw ScriptError(renderedFailure(Wire.failure(error)))
      }
      return .object([
        "path": .string(image.path),
        "mimeType": .string("image/png"),
        "bytes": .integer(image.bytes),
        "width": .integer(image.width),
        "height": .integer(image.height),
      ])
    })
    try engine.defineModule("wuhu:ai", source: aiModule)
  }
}

private let aiModule = #"""
const generate = __wuhu_generate_image
let signal
let guarded
globalThis.__wuhu_link_ai = (execution) => {
  ;({ signal, guarded } = execution)
}

const limit = \#(scriptImageConcurrency)
let running = 0
const waiting = []
const turn = () =>
  running < limit ? (running++, Promise.resolve()) : new Promise((resolve) => waiting.push(resolve))
const done = () => {
  const next = waiting.shift()
  if (next) next()
  else running--
}

export async function generateImage(prompt, options) {
  const destination = options?.destination
  if (typeof destination !== "string") throw new TypeError("generateImage needs { destination }")
  await turn()
  try {
    return await guarded(signal, () => generate(String(prompt), destination))
  } finally {
    done()
  }
}
"""#
